images:
  pullPolicy: IfNotPresent
  env: {}
  operator: bsgrigorov/helm-operator:latest
  pullPolicy: Always

service:
  port: 80

resources:
  requests:
    cpu: 0.125
    memory: 256Mi
  limits:
    cpu: 0.125
    memory: 256Mi