version: '3'
services:
  mp:
    image: bsgrigorov/helm-operator:latest
    build:
      context: .
      dockerfile: .
    environment:
      KUBECONFIG: /.kube/config/kubeconfig.yaml
    volumes:
      - $KUBECONFIG:/.kube/config/kubeconfig.yaml

