apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "name" . }}
  namespace:  {{.Release.Namespace }}
