apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "name" . }}
      containers:
      - name: {{ template "name" . }}
        image: {{ index .Values "images" "operator" }}
        imagePullPolicy: {{ .Values.images.pullPolicy }}
        env:
        - name: MY_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
  {{range $key,$value:= .Values.env}}
        - name: {{$key}}
          value: {{$value | quote}}
  {{end}}
        args:
        - "--leader-elect"
        - "--leader-election-id=helm-operator"
        - "--max-concurrent-reconciles=2" # used to limit concurrent tasks to avoid OOMKilled
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: {{.Values.service.port}}
      terminationGracePeriodSeconds: 10
